-- Migração 018: colunas IBS (reforma) em dbuf_n e dbmunicipio, do Oracle.
ALTER TABLE db_manaus.dbuf_n ADD COLUMN IF NOT EXISTS ibs numeric;
ALTER TABLE db_manaus.dbmunicipio ADD COLUMN IF NOT EXISTS ibs numeric;
UPDATE db_manaus.dbmunicipio SET ibs=0;
UPDATE db_manaus.dbuf_n SET ibs=0;
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='EX';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='AC';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='AL';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='AM';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='AP';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='BA';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='CE';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='DF';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='ES';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='GO';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='MA';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='MT';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='MS';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='MG';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='PA';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='PB';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='PR';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='PE';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='PI';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='RN';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='RS';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='RJ';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='RO';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='RR';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='SC';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='SP';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='SE';
UPDATE db_manaus.dbuf_n SET ibs=0.1 WHERE "UF"='TO';
