// components/campoParaAba.ts

export const campoParaAba: Record<string, string> = {
  // Dados Cadastrais
  tipo: 'dadosCadastrais',
  nome: 'dadosCadastrais',
  nomefantasia: 'dadosCadastrais',
  cnpj: 'dadosCadastrais',
  cpf: 'dadosCadastrais',
  cpf_cgc: 'dadosCadastrais',
  ie: 'dadosCadastrais',
  suframa: 'dadosCadastrais',
  email: 'dadosCadastrais',
  tipofornecedor: 'dadosCadastrais',
  tipoemp: 'dadosCadastrais',
  codcf: 'dadosCadastrais',
  codpais: 'dadosCadastrais',
  cep: 'dadosCadastrais',
  endereco: 'dadosCadastrais',
  numero: 'dadosCadastrais',
  bairro: 'dadosCadastrais',
  cidade: 'dadosCadastrais',
  uf: 'dadosCadastrais',
  complemento: 'dadosCadastrais',
  pais: 'dadosCadastrais',
  estado: 'dadosCadastrais',
  municipio: 'dadosCadastrais',
  fone1: 'dadosCadastrais',
  fone2: 'dadosCadastrais',
  contato: 'dadosCadastrais',
  celular: 'dadosCadastrais',
  iduf: 'dadosCadastrais',
  idmunicipio: 'dadosCadastrais',
  idpais: 'dadosCadastrais',
  imun: 'dadosCadastrais',
  iest: 'dadosCadastrais',
  isuframa: 'dadosCadastrais',

  // Dados Financeiros
  prazo: 'dadosFinanceiros',
  percdescfin: 'dadosFinanceiros',
  limcred: 'dadosFinanceiros',
  bloqueado: 'dadosFinanceiros',
  tipocobranca: 'dadosFinanceiros',
  tipofrete: 'dadosFinanceiros',
  formacobranca: 'dadosFinanceiros',
  observacao: 'dadosFinanceiros',
  clienteativo: 'dadosFinanceiros',
  clientevenda: 'dadosFinanceiros',
  clientefornecedor: 'dadosFinanceiros',
  clientetransportadora: 'dadosFinanceiros',
  clientefuncionario: 'dadosFinanceiros',
  clienteempresarial: 'dadosFinanceiros',
  clientepf: 'dadosFinanceiros',
  clientepj: 'dadosFinanceiros',
  idformacobranca: 'dadosFinanceiros',
  idtipofrete: 'dadosFinanceiros',
  idtipocobranca: 'dadosFinanceiros',

  // Regras de Faturamento
  tipoduplicata: 'regrasFaturamento',
  tipopreco: 'regrasFaturamento',
  transportadora: 'regrasFaturamento',
  vendedor: 'regrasFaturamento',
  condicaopagto: 'regrasFaturamento',
  tabelapreco: 'regrasFaturamento',
  tipotabela: 'regrasFaturamento',
  modalidadefrete: 'regrasFaturamento',
  listaregra: 'regrasFaturamento',
  idtransportadora: 'regrasFaturamento',
  idvendedor: 'regrasFaturamento',
  idcondpgto: 'regrasFaturamento',
  idtabelapreco: 'regrasFaturamento',
  idtipopreco: 'regrasFaturamento',
  idtipotabela: 'regrasFaturamento',
  idtipoduplicata: 'regrasFaturamento',
  idmodalidadefrete: 'regrasFaturamento',
};
